// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WalletPlusApi.Infrastructure.Persistence;

namespace WalletPlusApi.Infrastructure.Migrations
{
    [DbContext(typeof(WalletPlusApiContext))]
    partial class WalletPlusApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WalletPlusApi.Core.Data.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("EncryptionKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("OTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2021, 10, 31, 14, 49, 14, 592, DateTimeKind.Local).AddTicks(7170),
                            Email = "great@gmail.com",
                            FirstName = "ofe",
                            IsActive = false,
                            IsDeleted = false,
                            IsVerified = false,
                            LastName = "troy",
                            LastUpdated = new DateTime(2021, 10, 31, 14, 49, 14, 593, DateTimeKind.Local).AddTicks(4881)
                        });
                });

            modelBuilder.Entity("WalletPlusApi.Core.Data.MoneyWallet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BalanceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencySymbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("WalletId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("MoneyWallets");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BalanceAmount = 0.00m,
                            CreatedAt = new DateTime(2021, 10, 31, 14, 49, 14, 594, DateTimeKind.Local).AddTicks(6693),
                            CustomerId = 1L,
                            IsActive = false,
                            IsDeleted = false,
                            IsVerified = false,
                            LastUpdated = new DateTime(2021, 10, 31, 14, 49, 14, 594, DateTimeKind.Local).AddTicks(6702),
                            WalletId = "123456778"
                        });
                });

            modelBuilder.Entity("WalletPlusApi.Core.Data.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AmountAdded")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("BeneficiaryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DepositorId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWithdrawal")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopUpMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("WalletPlusApi.Core.Data.PointWallet", b =>
                {
                    b.HasBaseType("WalletPlusApi.Core.Data.MoneyWallet");

                    b.Property<decimal>("MoneyValueForPointEarned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PointEarned")
                        .HasColumnType("int");

                    b.ToTable("PointWallets");
                });

            modelBuilder.Entity("WalletPlusApi.Core.Data.MoneyWallet", b =>
                {
                    b.HasOne("WalletPlusApi.Core.Data.Customer", "Customer")
                        .WithOne("CustomerWallet")
                        .HasForeignKey("WalletPlusApi.Core.Data.MoneyWallet", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WalletPlusApi.Core.Data.Transaction", b =>
                {
                    b.HasOne("WalletPlusApi.Core.Data.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WalletPlusApi.Core.Data.PointWallet", b =>
                {
                    b.HasOne("WalletPlusApi.Core.Data.MoneyWallet", null)
                        .WithOne()
                        .HasForeignKey("WalletPlusApi.Core.Data.PointWallet", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WalletPlusApi.Core.Data.Customer", b =>
                {
                    b.Navigation("CustomerWallet");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
